meta_product_name: "Property AI"
meta_title: "Property AI - UK's Smartest Property Search"
meta_description: "Search engine for finding your dream house in the dream neighbourhood"
meta_image: "logo.png"
